2021-04-07 12:26:27,504 INFO: p8l startup [in /Users/sbuchl/Google Drive/htdocs/p8l/app/__init__.py:43]
2021-04-08 14:24:30,034 INFO: p8l startup [in /Users/sbuchl/Google Drive/htdocs/p8l/app/__init__.py:43]
2021-04-08 14:24:37,644 INFO: p8l startup [in /Users/sbuchl/Google Drive/htdocs/p8l/app/__init__.py:43]
2021-04-08 14:57:22,102 INFO: p8l startup [in /Users/sbuchl/Google Drive/htdocs/p8l/app/__init__.py:43]
2021-04-08 14:58:17,787 INFO: p8l startup [in /Users/sbuchl/Google Drive/htdocs/p8l/app/__init__.py:43]
2021-04-08 15:25:46,764 INFO: p8l startup [in /Users/sbuchl/Google Drive/htdocs/p8l/app/__init__.py:43]
2021-04-09 20:24:31,430 INFO: p8l startup [in /Users/sbuchl/Google Drive/htdocs/p8l/app/__init__.py:43]
2021-04-09 20:24:36,358 ERROR: Exception on /index [GET] [in /Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/app/routes.py", line 27, in index
    return render_template('index.html', title='P8lside', form=form, posts=posts)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/app/templates/index.html", line 21, in template
    {% inlude '_post.html' %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'inlude'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2021-04-09 20:24:51,688 ERROR: Exception on /index [GET] [in /Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/app/routes.py", line 27, in index
    return render_template('index.html', title='P8lside', form=form, posts=posts)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/app/templates/index.html", line 21, in template
    {% inlude '_post.html' %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'inlude'. Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.
2021-04-09 20:25:11,916 INFO: p8l startup [in /Users/sbuchl/Google Drive/htdocs/p8l/app/__init__.py:43]
2021-04-09 20:25:16,576 ERROR: Exception on /explore [GET] [in /Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/app/routes.py", line 47, in explore
    posts = Post.query.order_by(Post).timestamp.desc().all()
  File "<string>", line 2, in order_by
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/sqlalchemy/orm/base.py", line 227, in generate
    fn(self, *args[1:], **kw)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1948, in order_by
    criterion = self._adapt_col_list(criterion)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 340, in _adapt_col_list
    for o in cols
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 340, in <listcomp>
    for o in cols
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 4687, in _literal_as_label_reference
    return _literal_as_text(element)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 4730, in _literal_as_text
    return _literal_as(element, _no_text_coercion)
  File "/Users/sbuchl/Google Drive/htdocs/p8l/venv/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 4722, in _literal_as
    "instead" % type(element)
sqlalchemy.exc.ArgumentError: SQL expression object expected, got object of type <class 'flask_sqlalchemy.model.DefaultMeta'> instead
2021-04-09 20:26:27,182 INFO: p8l startup [in /Users/sbuchl/Google Drive/htdocs/p8l/app/__init__.py:43]
